apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "bootzooka.fullname" . }}-secret
data:
  SQL_PASSWORD: {{ tpl .Values.bootzooka.sql.password . | b64enc | quote }}
  SMTP_PASSWORD: {{ tpl .Values.bootzooka.smtp.password . | b64enc | quote }}
